config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "users/show" => "users#show"
  root to: "attendances#new"
  resources :attendances, only: [:new, :create, :destroy] do
    collection do
      get 'assist'
      get 'line'
    end
  end
  post "/" => "attendances#create"
  get "/attendances" => "attendances#new"
  resources :users, only: :show
  get "/users" => "attendances#new"
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="items-form-footer">
  <ul class="menu">
    <li><a href="https://bg8.power-k.jp/2I24E5D5" target="_blank">パワーナレッジで確認</a></li>
    <li><a href="https://www.chatwork.com/" target="_blank">ChatWorkで確認</a></li>
    <li><a href="https://drive.google.com/drive/u/0/folders/17jBXHMOA3Lt77V-w3gD2o-TYfVfp-suA" target="_blank">Googleドライブで確認</a></li>
  </ul>
  <%= link_to image_tag('IK.png' , size: '60x50'), "/" %>
  <p class="inc">
    ©︎IK,Inc.
  </p>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= image_tag("樹木.png", class:"second-logo") %>
    <%# <form class="search-form" action="#"> %>
      <%# <input class='input-box' placeholder='日付から出退勤の時間を調べる'> %>
      <%# <button class="search-button"> %>
      <%# </button> %>
    <%# </form> %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.full_name, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag('https://user-images.githubusercontent.com/71745650/100328030-66118900-300f-11eb-8ab2-f12ccccfb432.jpg', class:"second-logo"), "/" %>
</header>