config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "users/show" => "users#show"
  root to: "attendances#new"
  resources :attendances, only: [:new, :create, :destroy] do
    collection do
      get 'assist'
      get 'line'
    end
  end
  post "/" => "attendances#create"
  get "/attendances" => "attendances#new"
  resources :users, only: :show
  get "/users" => "attendances#new"
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :work_place
  validates :work_place, presence: true
  validates :work_place_id, numericality: { other_than: 1, message: 'を選んでください' }

  validates :work_days, presence: true
  validates :work_time, presence: true

  validates :in_out, inclusion: { in: [true, false], message: 'を選んでください' }
  validates :carfare, numericality: { only_integer: true, message: 'は半角数字で入力してください' }, allow_blank: true

  belongs_to :user
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:create, :assist, :destroy]

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)
    if @attendance.save
      $attendance = @attendance
      load 'spreadsheet/attendance.rb'
      @attendances = current_user.attendances.order(id: 'DESC')
    else
      render :new
    end
  end

  def assist
    load 'spreadsheet/assist.rb'
  end

  def line
    load 'spreadsheet/line.rb'
    redirect_to root_path
  end
  
  def destroy
    @attendance = Attendance.find(params[:id])
    $attendance = @attendance
    load 'spreadsheet/destroy.rb'
    @attendance.destroy if current_user.id == @attendance.user_id
    redirect_to users_show_path
  end

  private

  def attendance_params
    params.require(:attendance).permit(:work_place_id, :work_days, :in_out, :work_time, :carfare, :remarks).merge(user_id: current_user.id)
  end

  def set_user
    $user = current_user
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
  <%= render 'shared/error_messages', model: f.object %>

  <div class="img-upload">
  </div>
  <div class="new-items">
    <div class="weight-bold-text">
      勤務場所
      <span class="indispensable">必須</span>
    </div>

    <%= f.collection_select(:work_place_id, WorkPlace.all, :id, :name, {}, {class:"items-text", id:"attendance-work-place"}) %>
    <div class="items-explain">
      <div class="weight-bold-text">
        日付
        <span class="indispensable">必須</span>
      </div>
      <%= f.date_field :work_days, {class:"items-text", id:"attendance-work-days"} %>
    </div>
    
  </div>

  <div class="new-items">
    <div class="weight-bold-text">時刻
      <span class="indispensable">必須</span>
    </div>
      <%= f.time_field :work_time, {class:"items-text", id:"attendance-work-time"} %>
  </div>
    
  <div class="items-detail">
    <div class="weight-bold-text">出勤／退勤
      <span class="indispensable">必須</span>
    </div>
    <div class="form">
      <div class='radioArea'>
        <div class='radioArea-left'>
          <%= f.radio_button :in_out, :true, {style: "display: inline-block;"} %>
          <%= f.label :in_out_true, "出勤" %>
        </div>
        <div class='radioArea-right'>
          <%= f.radio_button :in_out, :false, {style: "display: inline-block;"} %>
          <%= f.label :in_out_false, "退勤" %>
        </div>
      </div>
    </div>

  <div class="form-carfare">
    <div class="weight-bold-text">交通費
      <span class="optional">任意</span>
    </div>
    <div>
      <div class="carfare-content">
        <span class="form-yen">¥　</span>
        <%= f.text_field :carfare, class:"carfare-input", id:"item-carfare", placeholder:"例）300" %>
      </div>
      <div class="carfare-content">
        <span>1日にかかった総額を入力</span>
      </div>
    </div>
    <div class="weight-bold-text">備考
      <span class="optional">任意</span>
    </div>
    <div>
      <div class="carfare-content">
        <%= f.text_field :remarks, class:"carfare-input", id:"item-carfare", placeholder:"例）〇〇講習会" %>
      </div>
    </div>
  </div>

  <%# 注意書き %>
  <div class="caution">
    <p class="sentence">
      勤務場所・日付・出/退勤・時刻は
    </p>
    <p class="sentence">
      必ず入力をご確認ください。
    </p>
  </div>
  <%# /注意書き %>

app/views/attendances/assist.html.erb
<%= render "shared/header" %>

<div class="contents row">
  <div class="success">
    <h3>入力処理が完了しました。</h3><br>
    <a class="btn" href="/">勤怠入力へ戻る</a>
  </div>
  <div class="items-form-title">
    <h5>LINE</h5>
    <%= link_to image_tag('line-brand-asset.png' , size: '60x60', class: "line-btn-icon"), line_attendances_path %>
    <div class='info-text'>勤怠管理の入力完了を<br>LINEで報告する<br>※メッセージが自動送信されます</div>
  </div>
</div>
<%= render "shared/footer"%>

app/views/attendances/create.html.erb
<%= render "shared/second-header"%>

<div class="contents row">
  <div class="success">
    <h3>入力が完了しました。</h3><br>
    <a class="btn" href="/">勤怠入力へ戻る</a>
  </div>

  <div class="attendances">
    <p class="rireki">出退勤入力履歴(最新10件まで)</p>
    <% @attendances.first(10).each do |attendance| %>
      <div class="content_post" >
        <%= WorkPlace.find(attendance.work_place_id).name %>
        <p class="attendances-info">
        <%= attendance.work_days %>
        <% if attendance.in_out %>
          <span>出</span>
        <% else %>
          <span>退</span>
        <% end %>
        <span class="name"><%= attendance.work_time.strftime("%H:%M") %></span>
        --
        <% if attendance.carfare.present? %>
          <%= "¥#{attendance.carfare}" %>
        <% end %>
        <%= link_to '削除', attendance_path(attendance.id), data: { confirm: "出退勤記録を取り消しますか？※勤務場所、交通費、備考記録も削除されます" }, method: :delete, class:'btn2' %>
        </p>
      </div>
    <% end %>
  </div>

  <div class="items-form-title">
    <div class='info-text'>※休憩時間、手当て、施術時間の入力<br>
    (翌月の勤怠を入力する前に行ってください)<br>
    ↓
    </div>
    <%= link_to '月末入力', assist_attendances_path, class: "getumatu-btn-icon" %>
  </div>
</div>
<%= render "shared/footer"%>

app/views/attendances/new.html.erb
<%= render "shared/header" %>

<div class="items-form-contents">
  <header class="items-form-header">
    <h2 class="items-form-title"><%= "#{current_user.full_name}さんの入力フォーム" %></h2>
  </header>
  <div class="items-form-main">
    <%= form_with model: @attendance, local: true do |f| %>
      <%= render partial: "form", locals: { f: f } %>
    </div>

    <div class='current-time-btn'>
      <span class='current-time-btn-text'>現時刻入力</span>
      <%= audio_tag("paka!!.mp3",id:"audio") %>  <%#音を鳴らす%>
      <button type="button" class="audioButton"></button>
      <%= javascript_tag do %>
        document.querySelector('.audioButton').onclick = function() {
        if( typeof( document.querySelector('#audio').currentTime ) !='undefined' )
        {
          document.querySelector('#audio').currentTime = 0;
        }
        document.querySelector("#audio").play();
        }
      <% end %>
      <%= image_tag '時計.png' , size: '60x60', class: "current-time-btn-icon"  %>
    </div>

    <div class="form-btn-contents">
      <%= f.submit "送信する" ,class:"form-btn" %>
    </div>
    <div class="items-form-title">
      <div class='info-text'>※休憩時間、手当て、施術時間の入力<br>
      (翌月の勤怠を入力する前に行ってください)<br>
      ↓
      </div>
      <%= link_to '月末処理', assist_attendances_path, class: "getumatu-btn-icon" %>
    </div>

  </div>
  <% end %>
  <%= render "shared/footer"%>
</div>